### ISSUE TITLE
[CODING] Создать мультиклассификатор при помощи подхода "one vs all"

### ISSUE THREAD

**Issue by rodinasophie** [SSL-GRENOBLE/SSL#4]
Для алгоритмов бинарной классификации необходимо создать расширение для использования их в качестве мультиклассификаторов.

**Comment by BorisovDm** [comment]
sklearn one-vs-one multiclass strategy: [link](https://scikit-learn.org/stable/modules/generated/sklearn.multiclass.OneVsOneClassifier.html#sklearn.multiclass.OneVsOneClassifier)
sklearn one-vs-all multiclass strategy: [link](https://scikit-learn.org/stable/modules/generated/sklearn.multiclass.OneVsRestClassifier.html)
