### ISSUE TITLE
[CODING][BUG] Проблема с --log ключом

### ISSUE THREAD

**Issue by rodinasophie** [SSL-GRENOBLE/SSL#9]
1. При явном выставлении --log параметра в False, параметр находится в состоянии True
2. Проблемы при открытии файла на логгирование на виндоуз 'C:\\Users\\sonya\\Desktop\\SSLLogs\\ssl_log_2019-12-03_20:40:16.txt'
Подозреваю, что дело в двоеточиях, т.к. это недопустимый символ на Windows.

**Comment by Vezzp** [comment]
1. Неправильное определение типа `type` переменной, которая передавалась в метод парсера`add_argument`.
2. Использовался недопустимый символ двоеточия в имени лог-файла при его создании в ОС Windows.
